name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker compose build
      - name: Run flake8
        run: docker compose run --rm app flake8 calc/

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker compose build
      - name: Run unit tests
        run: docker compose run --rm app pytest tests/test_calc.py -v

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker compose build
      - name: Run integration tests
        run: docker compose run --rm app pytest tests/test_api.py -v

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker compose build
      - name: Run E2E tests
        run: docker compose run --rm app pytest tests/test_e2e.py -v

  all-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker compose build
      - name: Run all tests
        run: |
          docker compose run --rm app flake8 calc/
          docker compose run --rm app pytest tests/ -v